<a href="https://colab.research.google.com/github/sam-kash/ML-Res/blob/main/medical_cost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mirichoi0218/insurance")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'insurance' dataset.
Path to dataset files: /kaggle/input/insurance


In [30]:
dataset = pd.read_csv("insurance.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [31]:
print(X)

[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]


In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,4,5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [37]:
print(X)

[[1.0 0.0 0.0 ... 19 27.9 0]
 [0.0 1.0 1.0 ... 18 33.77 1]
 [0.0 1.0 1.0 ... 28 33.0 3]
 ...
 [1.0 0.0 1.0 ... 18 36.85 0]
 [1.0 0.0 1.0 ... 21 25.8 0]
 [1.0 0.0 0.0 ... 61 29.07 0]]


In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=90)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

In [38]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 7391.58  6059.17]
 [ 3617.16  3309.79]
 [ 7241.19  5028.15]
 [15132.43 11396.9 ]
 [10723.77 24915.05]
 [19073.86 15555.19]
 [30061.87 20745.99]
 [32146.4  22462.04]
 [12867.47 10435.07]
 [10046.86  6551.75]
 [ 6342.27 18903.49]
 [ 9908.66  2927.06]
 [ 6964.42  8627.54]
 [ 6802.9   4466.62]
 [ 1091.55  2457.5 ]
 [10117.06 11070.53]
 [ -414.24  3167.46]
 [ 8853.03  6849.03]
 [25208.67 16884.92]
 [11619.29  7265.7 ]
 [12850.6  14001.13]
 [33893.65 39556.49]
 [ 5401.61  2498.41]
 [ 5372.8   3062.51]
 [ 9653.3   5428.73]
 [ 9513.07  9863.47]
 [ 7269.54  9264.8 ]
 [23573.13 13747.87]
 [ 4388.71  5209.58]
 [14673.66 13555.  ]
 [15369.99 10977.21]
 [10929.6  11082.58]
 [ 9575.14  5397.62]
 [10313.55 12957.12]
 [29835.12 37133.9 ]
 [32230.55 38746.36]
 [ 5399.08  6272.48]
 [ 6244.75  3925.76]
 [14943.63 36910.61]
 [30395.97 36950.26]
 [ 5853.53  2026.97]
 [ 9723.42  7633.72]
 [  978.75  2302.3 ]
 [31571.14 21677.28]
 [10584.29  4266.17]
 [34852.77 41034.22]
 [ 1164.48  2196.47]
 [17573.68 15